### ISSUE TITLE
Issue with new update

### ISSUE THREAD

**Issue by S0N-0F-A-S0N** [iAmGhost/VitaUpdateBlocker#6]
[Thu Jun 4 09:59:57 2015] Listening on 192.168.2.103:8080
[Thu Jun 4 09:59:57 2015] Blocking non-related traffic is DISABLED.
Traceback (most recent call last):
File "vita_update_blocker.py", line 131, in 
main()
File "vita_update_blocker.py", line 125, in main
config = proxy.ProxyConfig(port=port)
File "/Library/Python/2.7/site-packages/libmproxy/proxy/config.py", line 86, in init
CONF_BASENAME)
File "/Library/Python/2.7/site-packages/netlib/certutils.py", line 207, in from_store
dh = cls.load_dhparam(dh_path)
File "/Library/Python/2.7/site-packages/netlib/certutils.py", line 181, in load_dhparam
bio = OpenSSL.SSL._lib.BIO_new_file(path, b"r")
AttributeError: 'module' object has no attribute '_lib'

Using Python 2.7.6 & mitmproxy 0.12.1
This error shows.
(Yes, it is all installed correctly.)

Do you know of any VitaUpdateBlocker public servers? If I could get this to work, I'd run one myself. Unfortunately, as you can see it will not work & I'd be happy to find one.

**Comment by ethanx94** [comment]
+1

**Comment by iAmGhost** [comment]
Fixed by 2b9793e
