### ISSUE TITLE
Error while Vita attempts initial connect (system software 3.51)

### ISSUE THREAD

**Issue by michael-myers** [iAmGhost/VitaUpdateBlocker#7]
Traceback (most recent call last):
 File "vita_update_blocker.py", line 131, in <module>
   main()
 File "vita_update_blocker.py", line 128, in main
   m.run()
 File "vita_update_blocker.py", line 23, in run
   return controller.Master.run(self)
 File "/Users/tanuki/Desktop/mitmproxy/libmproxy/controller.py", line 122, in run
   self.tick(self.masterq, 0.1)
 File "/Users/tanuki/Desktop/mitmproxy/libmproxy/controller.py", line 108, in tick
   self.handle(*msg)
 File "/Users/tanuki/Desktop/mitmproxy/libmproxy/controller.py", line 129, in handle
   m(obj)
 File "vita_update_blocker.py", line 28, in handle_request
   if 'psp2-updatelist.xml' in msg.path and \
AttributeError: 'HTTPFlow' object has no attribute 'path'

**Comment by sl1pkn07** [comment]
same here
